### ISSUE TITLE
 http://localhost:9000/process.component.html 404 (Not Found)

### ISSUE THREAD

**Issue by tdinar** [gonzofish/semaphore-ng2-webpack#2]
Hi, thank you for the tutorial and the explanations towards how webpack works. I have spend sizable time trying to add new components to this starter and it is been failing. I am adding the component on the same level as the app of the question component and I am using the export from index.ts but it is not recognizing where the html is?  I also tried to import the class directly from the folder with no help. any tinkers I can utilize to help navigate this issue.  thanks again.

I found the issue, I had to use  "template:require('path')" instead of template:'path'.

**Comment by tdinar** [comment]
I found the issue, I had to use "template:require('path')" instead of "template:'path'" inside the component I added. I am not sure how to load css though

**Comment by gonzofish** [comment]
Glad you figured it out!

**Comment by gonzofish** [comment]
@tdinar i just saw you didn't understand how to load CSS...I hope you figured it out, too...if not there are a couple of ways. Components have two attributes to deal with this `styles` and `styleUrls`. Both take an array of styles. You can do any of the following:
- Using `styles` + `require` (similar to `template` + `require`):

``` javascript
// I know this way works with Webpack, not sure if it works without Webpack
styles: [require('./styles1.css'),require('../global-styles/styles2.css')]
```
- Using `styleUrls`

``` javascript
// I've never used this way, so I can't be 100% sure it works
stules: ['./styles1.css', '../global-styles/styles2.css']
```
- Using template strings

``` javascript
styles: [`
   body {
       color: red;
       margin: 5px;
   }
   .my-class { font-weight: bold; }
`]
```
