### ISSUE TITLE
Not hitting the subscription observers in the rest service specs

### ISSUE THREAD

**Issue by blakeparkinson** [gonzofish/semaphore-ng2-webpack#6]
In the rest service specs, the subscribe observer methods seem to never get hit, and the tests rather just assumes success.

**Comment by gonzofish** [comment]
I just realized this yesterday and I'll be making a change to ensure the tests are treated appropriately. Thanks for bringing it to my attention, though. I'll close this when the change has been made.

**Comment by gonzofish** [comment]
@blakeparkinson I've got another article coming out in a week, so I'm going to merge these changes in soon. If you want to make them in the meantime here there are:

**In `rest.service.ts`:**

[Line 7](https://github.com/gonzofish/semaphore-ng2-webpack/blob/master/src/services/rest.service.ts#L7): Remove the `Observable` import
[Line 24](https://github.com/gonzofish/semaphore-ng2-webpack/blob/master/src/services/rest.service.ts#L24): Change `json.data` to just `json`
[Line 28](https://github.com/gonzofish/semaphore-ng2-webpack/blob/master/src/services/rest.service.ts#L29): _Previously line 29_. Remove all the code in the `logError` method and replace it with:

```typescript
        console.error(error.error);
        throw error;
```

** In `rest.service.spec.ts`:**

[Line 52](https://github.com/gonzofish/semaphore-ng2-webpack/blob/master/src/services/rest.service.spec.ts#L52): Change `'/api/form'` to `api/forms`
[Line 62](https://github.com/gonzofish/semaphore-ng2-webpack/blob/master/src/services/rest.service.spec.ts#L62): Wrap `body` in an object with a `data` attribute. The result would be:

```typescript
      setupConnections(backend, {
            body: {
                data: [
                    {
                        id: 1,
                        questions: [],
                        title: 'Pizza'
                    },
                    {
                        id: 4,
                        questions: [],
                        title: 'Burrito'
                    },
                    {
                        id: 2,
                        questions: [],
                        title: 'Cheeseburger'
                    }
                ]
            },
            status: 200
        });
```

Again, thanks for bringing this to my attention and sorry if it caused any confusion. I'm not going to close this until I've merged in the new article's code which includes this fix.

**Comment by gonzofish** [comment]
Merged in fixes

**Comment by blakeparkinson** [comment]
@gonzofish thanks. I was using this as a reference and ran into a similar issue. Much appreciated!

**Comment by gonzofish** [comment]
Not a problem. I hate that I had bad code out in the open for all to see!
